export const CANVAS_BASE_WIDTH = 1280;
export const CANVAS_BASE_HEIGHT = 720;
export const GRAVITY = 10;
export const BASIC_PROJECTILE_VELOCITY = 30;
export const PROJECTILE_VISUALIZATION_INCREMENT = 0.5;
export const PROJECTILE_MOVEMENT_INCREMENT = 0.3;
export const MAX_PLAYER_LIVES = 5;
